matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="11"
    - os: linux
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="11"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - g++-8
            - g++-multilib
    - os: windows
      language: rust
      rust: nightly-2018-10-12
      env:
        - TRAVIS_NODE_VERSION="11"

cache: cargo

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-8"; fi
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use ${TRAVIS_NODE_VERSION}
  - node -v
  - npm -v
  - npm install

script:
  - cd test_module
  - npm run build
  - npm test
